/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReconciliationIndexRouteImport } from './routes/reconciliation.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AnalysisIndexRouteImport } from './routes/analysis.index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ConfigRulesRouteImport } from './routes/config.rules'
import { Route as ConfigModelsRouteImport } from './routes/config.models'
import { Route as ConfigDispositionRouteImport } from './routes/config.disposition'
import { Route as ConfigAgentsRouteImport } from './routes/config.agents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationIndexRoute = ReconciliationIndexRouteImport.update({
  id: '/reconciliation/',
  path: '/reconciliation/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRulesRoute = ConfigRulesRouteImport.update({
  id: '/config/rules',
  path: '/config/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigModelsRoute = ConfigModelsRouteImport.update({
  id: '/config/models',
  path: '/config/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigDispositionRoute = ConfigDispositionRouteImport.update({
  id: '/config/disposition',
  path: '/config/disposition',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigAgentsRoute = ConfigAgentsRouteImport.update({
  id: '/config/agents',
  path: '/config/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config/agents': typeof ConfigAgentsRoute
  '/config/disposition': typeof ConfigDispositionRoute
  '/config/models': typeof ConfigModelsRoute
  '/config/rules': typeof ConfigRulesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/agent/': typeof AgentIndexRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/reconciliation/': typeof ReconciliationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config/agents': typeof ConfigAgentsRoute
  '/config/disposition': typeof ConfigDispositionRoute
  '/config/models': typeof ConfigModelsRoute
  '/config/rules': typeof ConfigRulesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/agent': typeof AgentIndexRoute
  '/analysis': typeof AnalysisIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/reconciliation': typeof ReconciliationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config/agents': typeof ConfigAgentsRoute
  '/config/disposition': typeof ConfigDispositionRoute
  '/config/models': typeof ConfigModelsRoute
  '/config/rules': typeof ConfigRulesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/agent/': typeof AgentIndexRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/reconciliation/': typeof ReconciliationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config/agents'
    | '/config/disposition'
    | '/config/models'
    | '/config/rules'
    | '/orders/$orderId'
    | '/agent/'
    | '/analysis/'
    | '/orders/'
    | '/reconciliation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config/agents'
    | '/config/disposition'
    | '/config/models'
    | '/config/rules'
    | '/orders/$orderId'
    | '/agent'
    | '/analysis'
    | '/orders'
    | '/reconciliation'
  id:
    | '__root__'
    | '/'
    | '/config/agents'
    | '/config/disposition'
    | '/config/models'
    | '/config/rules'
    | '/orders/$orderId'
    | '/agent/'
    | '/analysis/'
    | '/orders/'
    | '/reconciliation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigAgentsRoute: typeof ConfigAgentsRoute
  ConfigDispositionRoute: typeof ConfigDispositionRoute
  ConfigModelsRoute: typeof ConfigModelsRoute
  ConfigRulesRoute: typeof ConfigRulesRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  AgentIndexRoute: typeof AgentIndexRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ReconciliationIndexRoute: typeof ReconciliationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation/': {
      id: '/reconciliation/'
      path: '/reconciliation'
      fullPath: '/reconciliation/'
      preLoaderRoute: typeof ReconciliationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/analysis'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/rules': {
      id: '/config/rules'
      path: '/config/rules'
      fullPath: '/config/rules'
      preLoaderRoute: typeof ConfigRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/models': {
      id: '/config/models'
      path: '/config/models'
      fullPath: '/config/models'
      preLoaderRoute: typeof ConfigModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/disposition': {
      id: '/config/disposition'
      path: '/config/disposition'
      fullPath: '/config/disposition'
      preLoaderRoute: typeof ConfigDispositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/agents': {
      id: '/config/agents'
      path: '/config/agents'
      fullPath: '/config/agents'
      preLoaderRoute: typeof ConfigAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigAgentsRoute: ConfigAgentsRoute,
  ConfigDispositionRoute: ConfigDispositionRoute,
  ConfigModelsRoute: ConfigModelsRoute,
  ConfigRulesRoute: ConfigRulesRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  AgentIndexRoute: AgentIndexRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ReconciliationIndexRoute: ReconciliationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
