// 4 个配置模块的 mock 数据
import type {
  RiskRule,
  MLModel,
  AgentConfig,
  KnowledgeBase,
  DispositionPolicy,
  FeedbackRecord,
} from "./pipeline-types";
import { CATEGORIES } from "./taxonomy";

// 简易种子随机
let seed = 20260421;
const rand = () => {
  seed = (seed * 9301 + 49297) % 233280;
  return seed / 233280;
};
const pick = <T>(arr: T[]) => arr[Math.floor(rand() * arr.length)];
const range = (min: number, max: number) => min + rand() * (max - min);
const intRange = (min: number, max: number) => Math.floor(range(min, max));

// =============== 风控规则 ===============
const RULE_TEMPLATES: { code: string; name: string; cat: typeof CATEGORIES[number]; cond: string; tags: string[] }[] = [
  { code: "R-FRD-001", name: "同设备多账号高频登录", cat: "fraud", cond: "device.account_count_1h > 5 AND geo.distinct_country_1h >= 2", tags: ["ATO", "团伙"] },
  { code: "R-FRD-002", name: "合成身份特征命中", cat: "fraud", cond: "id.synthetic_score > 0.85 AND age_days < 30", tags: ["合成身份", "新账户"] },
  { code: "R-FRD-003", name: "Headless 浏览器 + 大额", cat: "fraud", cond: "device.headless = true AND amount > 5000", tags: ["设备指纹"] },
  { code: "R-FRD-004", name: "信用卡 BIN 高风险国家", cat: "fraud", cond: "card.bin_country IN ('NG','RU','VE') AND amount > 1000", tags: ["盗刷"] },
  { code: "R-FRD-005", name: "钱骡账户特征", cat: "fraud", cond: "account.in_out_ratio > 0.92 AND tx_count_24h > 20", tags: ["Money Mule"] },
  { code: "R-FRD-006", name: "深度伪造活体检测命中", cat: "fraud", cond: "kyc.deepfake_score > 0.7", tags: ["Deepfake"] },
  { code: "R-FRD-007", name: "支付页面脚本异常", cat: "fraud", cond: "page.skimming_signature_match = true", tags: ["Magecart"] },
  { code: "R-BHV-001", name: "夜间大额海外交易", cat: "behavioral", cond: "hour BETWEEN 0 AND 5 AND amount > 10000 AND geo != home_country", tags: ["夜间", "大额"] },
  { code: "R-BHV-002", name: "短时高频小额刷单", cat: "behavioral", cond: "tx_count_5min > 8 AND avg_amount < 50", tags: ["刷单"] },
  { code: "R-BHV-003", name: "IP 跳变 (10分钟跨3国)", cat: "behavioral", cond: "ip.distinct_country_10min >= 3", tags: ["IP跳变"] },
  { code: "R-BHV-004", name: "支付方式突变", cat: "behavioral", cond: "channel != user.preferred_channel AND amount > 2000", tags: ["渠道突变"] },
  { code: "R-SYS-001", name: "回调超时 (>30s)", cat: "system", cond: "callback.elapsed_ms > 30000", tags: ["回调"] },
  { code: "R-SYS-002", name: "重复支付检测", cat: "system", cond: "duplicate_in_24h(order_no, amount, user_id)", tags: ["重复"] },
  { code: "R-REC-001", name: "渠道金额差异 > ¥1", cat: "reconciliation", cond: "ABS(internal_amount - channel_amount) > 1", tags: ["对账"] },
  { code: "R-REC-002", name: "结算 T+2 未到账", cat: "reconciliation", cond: "settle_pending_days >= 2", tags: ["结算"] },
  { code: "R-CHB-001", name: "近 30 天拒付率 > 1%", cat: "chargeback", cond: "merchant.chargeback_rate_30d > 0.01", tags: ["商户"] },
  { code: "R-CHB-002", name: "友好欺诈高频用户", cat: "chargeback", cond: "user.friendly_fraud_count_180d >= 3", tags: ["友好欺诈"] },
  { code: "R-MCH-001", name: "高风险行业商户", cat: "merchant", cond: "merchant.mcc IN ('7995','5967','6051')", tags: ["MCC"] },
  { code: "R-MCH-002", name: "商户退款率突增", cat: "merchant", cond: "merchant.refund_rate_7d / merchant.refund_rate_30d > 3", tags: ["突增"] },
  { code: "R-USR-001", name: "用户冲动消费提示", cat: "user", cond: "user.same_sku_count_5min >= 3", tags: ["误操作"] },
  { code: "R-CMP-001", name: "OFAC 黑名单命中", cat: "compliance", cond: "kyc.ofac_match = true", tags: ["AML", "黑名单"] },
  { code: "R-CMP-002", name: "AML 大额可疑 (¥50w+)", cat: "compliance", cond: "amount > 500000 AND aml.risk_level >= 'high'", tags: ["AML", "大额"] },
  { code: "R-CMP-003", name: "高风险行业 + 跨境", cat: "compliance", cond: "merchant.high_risk = true AND tx.cross_border = true", tags: ["跨境"] },
  { code: "R-FRD-008", name: "新设备 + 新IP + 新收款方", cat: "fraud", cond: "device.new = true AND ip.new = true AND payee.new = true", tags: ["三新"] },
  { code: "R-BHV-005", name: "登录与支付相隔 < 10s", cat: "behavioral", cond: "login_to_pay_seconds < 10 AND amount > 3000", tags: ["机器化"] },
];

const STATUSES = ["active", "active", "active", "shadow", "draft", "disabled"] as const;
const ACTIONS = ["intercept", "review", "score", "tag", "release"] as const;
const SCOPES = ["realtime", "realtime", "both", "offline"] as const;
const OWNERS = ["王小风", "陈安全", "李对账", "周合规", "Alex Chen", "Sarah Kim"];

export const MOCK_RULES: RiskRule[] = RULE_TEMPLATES.map((t, i) => {
  const status = STATUSES[i % STATUSES.length];
  const precision = range(0.72, 0.98);
  return {
    id: `rule-${i + 1}`,
    code: t.code,
    name: t.name,
    category: t.cat,
    description: `命中即按规则动作处理。AI 会持续监控该规则的精确率/召回率,若漂移则建议下线。`,
    status,
    scope: pick([...SCOPES]),
    priority: intRange(40, 100),
    condition: t.cond,
    action: pick([...ACTIONS]),
    scoreDelta: intRange(8, 45),
    hitCount24h: status === "disabled" ? 0 : intRange(20, 4800),
    hitCount7d: status === "disabled" ? 0 : intRange(200, 38000),
    precision,
    recall: range(0.55, 0.94),
    falsePositiveRate: range(0.005, 0.08),
    owner: pick(OWNERS),
    updatedAt: new Date(Date.now() - intRange(1, 30) * 86400000).toISOString(),
    createdAt: new Date(Date.now() - intRange(60, 720) * 86400000).toISOString(),
    version: intRange(1, 12),
    tags: t.tags,
  };
});

// =============== ML 模型 ===============
const FEATURE_POOL = [
  "amount", "channel", "hour_of_day", "device_age_days", "ip_country",
  "user_tx_count_30d", "merchant_chargeback_rate", "card_bin_country",
  "geo_distance_km", "device_fingerprint_match", "graph_neighbor_risk",
  "behavior_embedding", "session_duration", "login_method", "kyc_score",
];

export const MOCK_MODELS: MLModel[] = [
  {
    id: "model-fraud-gbdt",
    name: "欺诈识别 GBDT 主模型",
    algo: "GBDT",
    version: "v3.2.1",
    status: "online",
    category: "fraud",
    description: "基于 LightGBM 的二分类欺诈识别,实时打分主力模型,占融合权重 45%",
    threshold: 65,
    weight: 0.45,
    auc: 0.946,
    precision: 0.912,
    recall: 0.873,
    f1: 0.892,
    ks: 0.71,
    qps: 8432,
    p99Latency: 38,
    driftScore: 0.08,
    lastTrainedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    nextRetrainAt: new Date(Date.now() + 4 * 86400000).toISOString(),
    trainSamples: 12_400_000,
    features: FEATURE_POOL.slice(0, 12).map((n, i) => ({
      name: n,
      importance: range(0.02, 0.22),
      type: i < 6 ? "numeric" : i < 9 ? "categorical" : "embedding",
    })),
    owner: "王小风",
    abTestRatio: 1,
  },
  {
    id: "model-iforest",
    name: "孤立森林无监督异常",
    algo: "IsolationForest",
    version: "v1.8.0",
    status: "online",
    category: "behavioral",
    description: "无监督检测新型异常模式,捕捉规则未覆盖的长尾",
    threshold: 55,
    weight: 0.18,
    auc: 0.872,
    precision: 0.78,
    recall: 0.81,
    f1: 0.795,
    ks: 0.58,
    qps: 7820,
    p99Latency: 22,
    driftScore: 0.12,
    lastTrainedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    nextRetrainAt: new Date(Date.now() + 7 * 86400000).toISOString(),
    trainSamples: 8_200_000,
    features: FEATURE_POOL.slice(2, 10).map((n) => ({ name: n, importance: range(0.05, 0.2), type: "numeric" })),
    owner: "陈安全",
  },
  {
    id: "model-graphsage",
    name: "团伙图谱 GraphSAGE",
    algo: "GraphSAGE",
    version: "v2.0.3",
    status: "online",
    category: "fraud",
    description: "基于设备/IP/收款方关系图的团伙识别,捕捉欺诈集群",
    threshold: 70,
    weight: 0.22,
    auc: 0.918,
    precision: 0.89,
    recall: 0.76,
    f1: 0.82,
    ks: 0.66,
    qps: 1240,
    p99Latency: 142,
    driftScore: 0.15,
    lastTrainedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    nextRetrainAt: new Date(Date.now() + 1 * 86400000).toISOString(),
    trainSamples: 4_800_000,
    features: ["graph_neighbor_risk", "graph_community_size", "graph_centrality", "shared_device_count", "shared_ip_count"].map(
      (n) => ({ name: n, importance: range(0.1, 0.3), type: "graph" }),
    ),
    owner: "Alex Chen",
  },
  {
    id: "model-deepfm",
    name: "DeepFM 行为序列模型",
    algo: "DeepFM",
    version: "v1.4.2",
    status: "shadow",
    category: "behavioral",
    description: "影子模式运行中,与 GBDT 对比 A/B,准备下季度上线",
    threshold: 60,
    weight: 0.15,
    auc: 0.952,
    precision: 0.918,
    recall: 0.88,
    f1: 0.899,
    ks: 0.73,
    qps: 0,
    p99Latency: 48,
    driftScore: 0.06,
    lastTrainedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    nextRetrainAt: new Date(Date.now() + 5 * 86400000).toISOString(),
    trainSamples: 15_600_000,
    features: FEATURE_POOL.map((n, i) => ({
      name: n,
      importance: range(0.02, 0.18),
      type: i < 8 ? "numeric" : "embedding",
    })),
    owner: "Sarah Kim",
    abTestRatio: 0.1,
  },
  {
    id: "model-autoencoder",
    name: "AutoEncoder 对账异常",
    algo: "AutoEncoder",
    version: "v1.2.0",
    status: "online",
    category: "reconciliation",
    description: "对账差异重建误差检测,识别长尾对账异常",
    threshold: 50,
    weight: 0.6,
    auc: 0.901,
    precision: 0.86,
    recall: 0.79,
    f1: 0.823,
    ks: 0.62,
    qps: 320,
    p99Latency: 18,
    driftScore: 0.09,
    lastTrainedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    nextRetrainAt: new Date(Date.now() + 9 * 86400000).toISOString(),
    trainSamples: 2_100_000,
    features: ["amount_diff", "ts_diff", "fee_pct", "fx_rate_diff", "ref_match_score"].map((n) => ({
      name: n,
      importance: range(0.1, 0.3),
      type: "numeric",
    })),
    owner: "李对账",
  },
  {
    id: "model-xgb-chargeback",
    name: "拒付预测 XGBoost",
    algo: "XGBoost",
    version: "v2.1.0",
    status: "online",
    category: "chargeback",
    description: "T+0 预测未来 30 天拒付概率,辅助商户风控",
    threshold: 60,
    weight: 0.3,
    auc: 0.887,
    precision: 0.82,
    recall: 0.74,
    f1: 0.778,
    ks: 0.59,
    qps: 480,
    p99Latency: 28,
    driftScore: 0.11,
    lastTrainedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    nextRetrainAt: new Date(Date.now() + 8 * 86400000).toISOString(),
    trainSamples: 3_400_000,
    features: FEATURE_POOL.slice(4, 12).map((n) => ({ name: n, importance: range(0.04, 0.22), type: "numeric" })),
    owner: "周合规",
  },
  {
    id: "model-bert-text",
    name: "BERT 文本风险分类",
    algo: "DeepFM",
    version: "v0.9.1",
    status: "training",
    category: "compliance",
    description: "对商户描述/订单备注做文本风险分类,捕捉违规话术",
    threshold: 50,
    weight: 0.1,
    auc: 0.83,
    precision: 0.76,
    recall: 0.7,
    f1: 0.728,
    ks: 0.5,
    qps: 0,
    p99Latency: 0,
    driftScore: 0,
    lastTrainedAt: new Date(Date.now() - 0.5 * 86400000).toISOString(),
    nextRetrainAt: new Date(Date.now() + 14 * 86400000).toISOString(),
    trainSamples: 980_000,
    features: ["text_embedding", "keyword_hit", "sentiment_score"].map((n) => ({
      name: n,
      importance: range(0.1, 0.4),
      type: "embedding",
    })),
    owner: "Sarah Kim",
  },
];

// =============== 知识库 ===============
export const MOCK_KBS: KnowledgeBase[] = [
  {
    id: "kb-rules",
    name: "风控规则知识库",
    type: "rule_doc",
    documentCount: 348,
    vectorCount: 12_400,
    lastIndexedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    embedding: "bge-large-zh",
  },
  {
    id: "kb-cases",
    name: "历史案例库 (近 2 年)",
    type: "case_history",
    documentCount: 18_420,
    vectorCount: 84_200,
    lastIndexedAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    embedding: "bge-large-zh",
  },
  {
    id: "kb-regulation",
    name: "合规法规库",
    type: "regulation",
    documentCount: 96,
    vectorCount: 4_820,
    lastIndexedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    embedding: "text-embedding-3-large",
  },
  {
    id: "kb-merchant",
    name: "商户画像库",
    type: "merchant_profile",
    documentCount: 42_100,
    vectorCount: 168_400,
    lastIndexedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    embedding: "m3e-large",
  },
  {
    id: "kb-fraud-pattern",
    name: "欺诈模式图谱",
    type: "fraud_pattern",
    documentCount: 1_240,
    vectorCount: 9_840,
    lastIndexedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    embedding: "bge-large-zh",
  },
];

// =============== AI Agent ===============
export const MOCK_AGENTS: AgentConfig[] = [
  {
    id: "agent-rca",
    name: "根因分析 Agent",
    description: "对中高风险订单做多模态因果推理 + RAG 检索,生成结构化根因报告",
    enabled: true,
    provider: "qwen-max",
    model: "qwen-max-2025-04",
    temperature: 0.2,
    topP: 0.9,
    maxTokens: 4096,
    triggers: ["auto", "rule_escalation"],
    triggerScore: 65,
    triggerCategories: ["fraud", "behavioral", "chargeback"],
    enableMultimodal: true,
    enableCausalGraph: true,
    enableRAG: true,
    ragTopK: 8,
    ragKnowledgeBases: ["kb-rules", "kb-cases", "kb-fraud-pattern"],
    tools: [
      { name: "queryGraph", description: "查询团伙关系图谱", enabled: true, callCount24h: 1248 },
      { name: "fetchUserHistory", description: "拉取用户 90 天行为", enabled: true, callCount24h: 2104 },
      { name: "checkBlacklist", description: "黑名单/制裁名单查询", enabled: true, callCount24h: 1820 },
      { name: "executeAction", description: "调用支付网关执行处置", enabled: true, callCount24h: 412 },
      { name: "generateChargebackReply", description: "生成拒付申诉文案", enabled: false, callCount24h: 0 },
    ],
    systemPrompt:
      "你是支付风控领域的资深分析师。请基于订单数据 + 命中规则 + ML 评分 + RAG 检索结果,输出结构化根因报告:1)根因总结 2)关键证据(带权重) 3)推荐动作 Top3。所有结论必须可追溯到证据。禁止编造未在证据中出现的事实。",
    enableHallucinationCheck: true,
    enableFactGrounding: true,
    enableSensitiveFilter: true,
    callCount24h: 8420,
    avgLatencyMs: 1420,
    avgTokens: 1847,
    costUSD24h: 42.18,
    hallucinationRate: 0.012,
  },
  {
    id: "agent-recon",
    name: "对账差异 Agent",
    description: "对账异常自动归因,生成调整凭证建议",
    enabled: true,
    provider: "deepseek-v3",
    model: "deepseek-v3-2025",
    temperature: 0.1,
    topP: 0.85,
    maxTokens: 2048,
    triggers: ["auto"],
    triggerScore: 0,
    triggerCategories: ["reconciliation"],
    enableMultimodal: true,
    enableCausalGraph: false,
    enableRAG: true,
    ragTopK: 5,
    ragKnowledgeBases: ["kb-rules", "kb-merchant"],
    tools: [
      { name: "queryChannelStatement", description: "查询渠道流水", enabled: true, callCount24h: 4820 },
      { name: "generateVoucher", description: "生成会计调整凭证", enabled: true, callCount24h: 1284 },
    ],
    systemPrompt: "你是对账专家。基于内部流水 + 渠道流水,识别差异类型(时序/金额/汇率/手续费),输出根因 + 调整凭证建议。",
    enableHallucinationCheck: true,
    enableFactGrounding: true,
    enableSensitiveFilter: false,
    callCount24h: 4820,
    avgLatencyMs: 820,
    avgTokens: 1240,
    costUSD24h: 18.4,
    hallucinationRate: 0.008,
  },
  {
    id: "agent-chargeback",
    name: "拒付申诉 Agent",
    description: "针对欺诈/友好欺诈拒付自动生成申诉材料",
    enabled: false,
    provider: "gpt-4o",
    model: "gpt-4o-2025",
    temperature: 0.4,
    topP: 0.95,
    maxTokens: 3000,
    triggers: ["manual"],
    triggerScore: 0,
    triggerCategories: ["chargeback"],
    enableMultimodal: false,
    enableCausalGraph: false,
    enableRAG: true,
    ragTopK: 6,
    ragKnowledgeBases: ["kb-cases", "kb-regulation"],
    tools: [
      { name: "fetchEvidence", description: "拉取交易证据 (物流/IP/设备)", enabled: true, callCount24h: 0 },
      { name: "generateLetter", description: "生成英文申诉信", enabled: true, callCount24h: 0 },
    ],
    systemPrompt: "你是争议处理专家。基于拒付原因码(Reason Code)+ 商户证据,生成符合卡组织模板的英文申诉文案。",
    enableHallucinationCheck: true,
    enableFactGrounding: true,
    enableSensitiveFilter: true,
    callCount24h: 0,
    avgLatencyMs: 0,
    avgTokens: 0,
    costUSD24h: 0,
    hallucinationRate: 0,
  },
];

// =============== 自动处置策略 ===============
export const MOCK_POLICIES: DispositionPolicy[] = [
  {
    id: "pol-1",
    name: "致命欺诈 → 立即拦截 + 强制 2FA",
    description: "AI 置信度 ≥95% 且风险分 ≥85,直接拦截并冻结二次验证",
    enabled: true,
    priority: 100,
    category: "fraud",
    riskLevel: "critical",
    minScore: 85,
    minConfidence: 95,
    primaryAction: "intercept",
    secondaryActions: ["force_2fa", "watchlist", "notify_user"],
    autoExecute: true,
    requireHumanApproval: false,
    notifyChannels: ["webhook", "im"],
    feedbackRequired: true,
    cooldownMinutes: 60,
    executedCount24h: 248,
    successRate: 0.982,
    reversedCount24h: 4,
    avgProcessingMs: 320,
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "pol-2",
    name: "高风险 → 人工复核",
    description: "65 ≤ 风险分 < 85,挂起订单进入复核队列",
    enabled: true,
    priority: 80,
    category: "all",
    riskLevel: "high",
    minScore: 65,
    minConfidence: 70,
    primaryAction: "review",
    secondaryActions: ["notify_user"],
    autoExecute: true,
    requireHumanApproval: false,
    notifyChannels: ["im"],
    feedbackRequired: true,
    cooldownMinutes: 0,
    executedCount24h: 1820,
    successRate: 0.94,
    reversedCount24h: 38,
    avgProcessingMs: 180,
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "pol-3",
    name: "对账差异 → 自动生成凭证",
    description: "AI 识别的对账差异(置信度 ≥90)自动生成会计调整凭证",
    enabled: true,
    priority: 70,
    category: "reconciliation",
    riskLevel: "all",
    minScore: 0,
    minConfidence: 90,
    primaryAction: "auto_refund",
    secondaryActions: [],
    autoExecute: true,
    requireHumanApproval: true,
    notifyChannels: ["email"],
    feedbackRequired: false,
    cooldownMinutes: 0,
    executedCount24h: 412,
    successRate: 0.968,
    reversedCount24h: 6,
    avgProcessingMs: 240,
    updatedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: "pol-4",
    name: "OFAC 命中 → 立即冻结 + 上报",
    description: "黑名单/制裁名单命中,冻结账户并上报合规",
    enabled: true,
    priority: 100,
    category: "compliance",
    riskLevel: "critical",
    minScore: 0,
    minConfidence: 99,
    primaryAction: "freeze_account",
    secondaryActions: ["add_blacklist", "escalate"],
    autoExecute: true,
    requireHumanApproval: false,
    notifyChannels: ["email", "webhook"],
    feedbackRequired: true,
    cooldownMinutes: 1440,
    executedCount24h: 12,
    successRate: 1,
    reversedCount24h: 0,
    avgProcessingMs: 420,
    updatedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: "pol-5",
    name: "中风险 → 加观察名单 30 天",
    description: "40 ≤ 风险分 < 65,放行但加入观察名单",
    enabled: true,
    priority: 50,
    category: "behavioral",
    riskLevel: "medium",
    minScore: 40,
    minConfidence: 60,
    primaryAction: "watchlist",
    secondaryActions: [],
    autoExecute: true,
    requireHumanApproval: false,
    notifyChannels: [],
    feedbackRequired: false,
    cooldownMinutes: 0,
    executedCount24h: 3240,
    successRate: 0.91,
    reversedCount24h: 12,
    avgProcessingMs: 80,
    updatedAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: "pol-6",
    name: "拒付高频商户 → 升级人工",
    description: "拒付率突增的商户订单升级到人工",
    enabled: false,
    priority: 60,
    category: "chargeback",
    riskLevel: "high",
    minScore: 50,
    minConfidence: 80,
    primaryAction: "escalate",
    secondaryActions: ["notify_user"],
    autoExecute: false,
    requireHumanApproval: true,
    notifyChannels: ["email", "im"],
    feedbackRequired: true,
    cooldownMinutes: 720,
    executedCount24h: 0,
    successRate: 0,
    reversedCount24h: 0,
    avgProcessingMs: 0,
    updatedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
];

// =============== 反馈记录 ===============
const REVIEWERS = ["王小风", "陈安全", "李对账", "周合规", "Alex Chen", "Sarah Kim", "Tom Liu"];
const FEEDBACK_TYPES = ["confirm", "confirm", "confirm", "override", "false_positive", "partial_correct"] as const;
const ACTIONS_POOL: Array<import("./pipeline-types").DispositionAction> = [
  "intercept", "review", "release", "auto_refund", "force_2fa", "watchlist",
];

export const MOCK_FEEDBACK: FeedbackRecord[] = Array.from({ length: 64 }, (_, i) => {
  const fbType = FEEDBACK_TYPES[i % FEEDBACK_TYPES.length];
  const aiAct = pick(ACTIONS_POOL);
  const finalAct = fbType === "confirm" ? aiAct : pick(ACTIONS_POOL);
  return {
    id: `fb-${i + 1}`,
    orderNo: `PAY${20260400000 + intRange(1, 99999)}`,
    originalAction: aiAct,
    aiSuggestion: aiAct,
    finalAction: finalAct,
    reviewer: pick(REVIEWERS),
    reviewedAt: new Date(Date.now() - intRange(1, 168) * 3600000).toISOString(),
    isCorrect: fbType === "confirm",
    feedbackType: fbType,
    comment: pick([
      "证据充分,AI 判断准确,直接确认",
      "用户已二次验证通过,改为放行",
      "误杀,客户为长期老客户,改为观察",
      "AI 漏判了团伙特征,补充规则建议",
      "对账差异为 T+1 时序,建议规则收紧",
      "申诉材料齐全,改为人工放行",
    ]),
    fedToRAG: rand() > 0.2,
    fedToTraining: rand() > 0.4,
    ruleSuggestion: rand() > 0.7 ? "建议新增: 同IP /24 段 + 新设备 + >¥3000 → review" : undefined,
    estimatedSavedLoss: rand() > 0.5 ? Math.round(range(500, 28000)) : undefined,
  };
});
